### ISSUE TITLE
Referencing Bug

### ISSUE THREAD

**Issue by cool-Blue** [mantoni/brout.js#4]
Hi, this is really cool, I'm a big fan of isomorphic code and yours is super elegant...

I noticed small issue though: when there are no listeners, `stdout` always writes to `info` and `stderror` to `warn` instead of `log` and `error` respectively.  I figured out why...

Take `log` and `info` for example.  
because you did this
```js
console.info  = console.log
```
when you do this
```js
console.log.original   = originalLog;
console.info.original  = originalInfo;
```
your actually doing this

```js
console.log.original   = originalLog;
console.log.original  = originalInfo;
```
because `console.info` is already `console.log`, so the `.original` member resolves to `console.log.original`.  That's why `stdout` is logging to the `info` channel.

The easy fix is to replace this code
```js
redirectLog('log', 'stdout');
redirectLog('warn', 'stderr');
console.info  = console.log;
console.error = console.warn;
```
with this
```js
redirectLog('log', 'stdout');
redirectLog('info', 'stdout');
redirectLog('warn', 'stderr');
redirectLog('error', 'stderr');
```
... if you want to keep that functionality.
For me I would prefer to keep the `info` and `warn` channels free since, technically, they don't map onto node.  Therefore I would suggest this...
```js
redirectLog('log', 'stdout');
redirectLog('error', 'stderr');
```

**Comment by mantoni** [comment]
Thanks. This is unintentional and your suggested change seems fine.
Care to put this in a pull request?

**Comment by cool-Blue** [comment]
OK, great.  Yep, I will come back later with the PR.
