### ISSUE TITLE
'log traces' test fails on on phantomJS 2.2.1 Windows 10

### ISSUE THREAD

**Issue by cool-Blue** [mantoni/brout.js#7]
The formatting of the stack traces do not like `/?=^\s+at\s+/`, they are actually like `/^.*@http:\/\/.+/` This is causing the final test to fail.

**Comment by mantoni** [comment]
Thanks for reporting. This seems to be an issue with `phantomic` as the test suite over there has currently the same issue (see https://github.com/mantoni/phantomic/issues/14).

This used to pass on PhantomJS 1.9, but 2.0 seems to have a new stack-trace format.

**Comment by cool-Blue** [comment]
I did this to fix it and keep backward compatibility...
```js
      lines.slice(0, l - 1).forEach(function (line, i) {
        if (i !== l - 1) {
          assert.ok(!!line.match(/(?=^\s+at\s+)|(^.*@http:\/\/.+)/), line);
        } else {
          assert.equal(lines[lines.length - 1], '');
        }
```

**Comment by mantoni** [comment]
Yes. This is a workaround. The actual issue is that the source mapper should produce a consistent output. If we can fix it in Phantomic, I expect this issue to disappear here.

**Comment by mantoni** [comment]
Can this be closed?

**Comment by cool-Blue** [comment]
Sure, no problem.  Sorry, I thought it was closed by the merge.
